language: node_js
cache:
  directories:
  - webapp/
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_887081f0f551_key -iv $encrypted_887081f0f551_iv -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- git submodule init
- git submodule update
- cd webapp/open-budget
install:
- npm install
script: 
- npm run lint && npm run build 
- cd ../../open-budget-il

deploy:
  provider: gae
  keyfile: open-budget-il-aaf0a776a535.json
  project: open-budget-il
  version: 4
  no_promote: true
  on: 
    branch: travis-deploy
