language: node_js
cache:
  directories:
  - webapp/
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_575e6db9695c_key -iv $encrypted_575e6db9695c_iv -in ./open-budget-il/open-budget-il-aaf0a776a535.json.enc -out ./open-budget-il/open-budget-il-aaf0a776a535.json -d
- git submodule init
- cd webapp
- git checkout master -f
- git pull origin master
- cd open-budget
install:
- npm install
script: 
- npm run lint && npm run build 

deploy:
  provider: gae
  keyfile: open-budget-il-aaf0a776a535.json
  project: open-budget-il
  version: staging
  no_promote: true
  on: 
    branch: travis-deploy
