language: node_js
cache:
  directories:
  - webapp/
node_js:
- stable
before_install:
- openssl aes-256-cbc -K $encrypted_887081f0f551_key -iv $encrypted_887081f0f551_iv -in secrets.tar.enc -out secrets.tar -d
- tar -xvf secrets.tar
- git submodule init
- git submodule update
install:
- cd webapp/open-budget
- npm install
- cd ../email
- npm install
- cd ../../
script: 
- cd webapp/open-budget && npm run lint && npm run build && cd ../../
- cd webapp/email && npm run build && cd ../../
- cd open-budget-il

deploy:
  provider: gae
  keyfile: open-budget-il-aaf0a776a535.json
  project: open-budget-il
  version: staging
  no_promote: true
  on: 
    branch: travis-deploy
