application: open-budget-il
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.api
- url: /rss/.*
  script: main.api
- url: /report/api/.*
  script: main.report
- url: /report/app/
  static_files: coming-soon/index.html
  upload: webapp/dist/
- url: /report/app/(.+)
  static_files: coming-soon/\1
  upload: coming-soon/
- url: /report/go/
  static_files: webapp/dist/index.html
  upload: webapp/dist/
- url: /static/email/img/(.+)
  static_files: webapp/email/img/\1
  upload: webapp/email/img/
- url: /report/go/(.+)
  static_files: webapp/dist/\1
  upload: webapp/dist/
- url: /stg/
  static_files: webapp/main/index.html
  upload: webapp/main/
- url: /stg/(.+)
  static_files: webapp/main/\1
  upload: webapp/main/

- url: /change_input/dist
  static_dir: change_input/dist
- url: /change_input/.*
  script: change_input.precommittee.application

builtins:
- remote_api: on
- appstats: on
- deferred: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

instance_class: F4
automatic_scaling:
  max_pending_latency: 200ms
