application: open-budget-il
version: 2
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /api/.*
  script: main.api
- url: /api
  static_files: docs/api.html
  upload: docs/
- url: /rss/.*
  script: main.api
- url: /report/api/.*
  script: main.report
- url: /email/
  static_files: webapp/emaildist/index.html
  upload: webapp/emaildist/
- url: /email/(.+)
  static_files: webapp/emaildist/\1
  upload: webapp/emaildist/
- url: /report/go/
  static_files: webapp/dist/index.html
  upload: webapp/dist/
- url: /static/email/img/(.+)
  static_files: webapp/email/img/\1
  upload: webapp/email/img/
- url: /report/go/(.+)
  static_files: webapp/dist/\1
  upload: webapp/dist/

- url: /tasks/.*
  script: main.tasks

- url: /redirect/.*
  static_files: redirector/redirector.html
  upload: redirector

- url: /change_input/dist
  static_dir: change_input/dist
- url: /change_input/.*
  script: change_input.precommittee.application

- url: /gov/api.*
  script: gov.gov
- url: /gov/
  static_files: gov/obudget.html
  upload: gov/
- url: /gov/(.+)
  static_files: gov/\1
  upload: gov/

- url: /
  static_files: webapp/main/index.html
  upload: webapp/main/
- url: /(.+)
  static_files: webapp/main/\1
  upload: webapp/main/

builtins:
- remote_api: on
- deferred: on
#- appstats: on

libraries:
- name: webapp2
  version: latest
- name: jinja2
  version: latest

instance_class: F1
automatic_scaling:
  min_pending_latency: 200ms
  max_pending_latency: 500ms
  min_idle_instances: 0
  max_idle_instances: 1
